// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs7IMLiRpEjEIVm8px8ilQS5xyEibw-gk',
    appId: '1:393838006079:web:59aa0a0780c5c6153c0d8a',
    messagingSenderId: '393838006079',
    projectId: 'gym-ai-ba330',
    authDomain: 'gym-ai-ba330.firebaseapp.com',
    storageBucket: 'gym-ai-ba330.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC70_gp1novuWmZhW1R-TUo6edvMvEz2IU',
    appId: '1:393838006079:android:3de8ccd73c71eb093c0d8a',
    messagingSenderId: '393838006079',
    projectId: 'gym-ai-ba330',
    storageBucket: 'gym-ai-ba330.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs7IMLiRpEjEIVm8px8ilQS5xyEibw-gk',
    appId: '1:393838006079:web:04c5b618b0a38cc93c0d8a',
    messagingSenderId: '393838006079',
    projectId: 'gym-ai-ba330',
    authDomain: 'gym-ai-ba330.firebaseapp.com',
    storageBucket: 'gym-ai-ba330.firebasestorage.app',
  );
}
